SECRET_KEY = 'YOUR_SECRET_KEY'

DATABASE_NAME = ''
DATABASE_USER = ''
DATABASE_PASSWORD = ''
DATABASE_HOST = ''

PHOTOS_LOCATION = ''
PHOTOS_SERVER = ''

RECAPTCHA_PUBLIC_KEY = 'MyRecaptchaKey123'
RECAPTCHA_PRIVATE_KEY = 'MyRecaptchaPrivateKey456'

CMS_ADMIN_LOGIN = 'admin'
CMS_ADMIN_PASSWORD = 'admin'
